### ISSUE TITLE
Search History Breaks with nvim nightly and incsearch

### ISSUE THREAD

**Issue by joshuarubin** [kevinhwang91/nvim-hlslens#18] opened 2021-10-07 18:31 UTC
Using a recent nvim nightly, if I start a search and type `<up>` I can't iterate through the search history anymore, it just gets stuck and the up and down arrows stop working. Disabling incsearch fixes things. This only started after a recent upgrade of nvim.

**Comment by joshuarubin** [comment] 2021-10-08 18:22
> After spending a few hours, I have no idea how to solve this issue. :(

Glad you were able to reproduce the issue with my fairly vague description! Do we need to bring this up with the neovim team? Have you been able to identify anything more specific about what you're doing that causes the bug?

**Comment by kevinhwang91** [comment] 2021-10-09 02:58
It's not a bug of neovim team. Just an implement by hlslens to add lens in incsearch is a trick.

When hlslens want to refresh the lens, it will make neovim emit `<C-r><Esc>` to update the screen. Even though users can't feel any side effects, neovim will change the inner command buffer while receiving extra `<C-r><Esc>`  . Unfortunately, `<Up>` and `<Down>` will search results according to the current inner command buffer. I think we should disable to refresh lens while pressing `<Up>` and `<Down>`.

**Comment by kevinhwang91** [comment] 2022-09-24 15:14
Has reworked the module, fixed now.

**Closed by kevinhwang91** 2022-09-24 15:14 UTC
Labels: bug
