### ISSUE TITLE
invalid in command-line window errors

### ISSUE THREAD

**Issue by jemag** [kevinhwang91/nvim-hlslens#9] opened 2021-05-24 17:07 UTC
- `nvim --version`:NVIM v0.5.0-dev+1327-gdc18c1e3e
- Operating system/version: Arch Linux /  Linux 5.12.4-arch1-2

**Describe the bug**
Searching text within the command-line window (`q:`) will trigger the following error
![image](https://user-images.githubusercontent.com/7985687/119381876-4fcb4980-bc8f-11eb-83ee-76e33017148d.png)

1. Press `q:`
2. Use `?` to search within command-line window
3. Witness the error

**Expected behavior**
Not sure if hlslens can work within the command-line window. Expected behavior would be for it to either work, or gracefully handle the error.

**Comment by kevinhwang91** [comment] 2021-05-24 17:12
https://github.com/kevinhwang91/nvim-hlslens/commit/4a5268bff73e43792f2d216a52ae19507da5c866

**Comment by kevinhwang91** [comment] 2021-05-24 17:42
I add an extra patch for this issue because the `BufWinEnter` in https://github.com/kevinhwang91/nvim-hlslens/commit/6ca5fc6cd9fab32039a73bba4f14d33d47e87953 broke the previous https://github.com/kevinhwang91/nvim-hlslens/commit/4a5268bff73e43792f2d216a52ae19507da5c866.

**Comment by jemag** [comment] 2021-05-24 20:58
Error is still there, I am on commit 58ff4896df9c92ba081f4e89a7539d99786d7a88 
![image](https://user-images.githubusercontent.com/7985687/119405574-74cfb480-bcaf-11eb-86e0-7b468b7a5142.png)

Don't know much about your code, but I am not getting the error if I comment the lines 108-109
```lua
        -- cmd(('sil noa %dchi'):format(hls_qf_nr))
        -- cmd([[noa call setqflist([], 'r')]])
```
and line 137
```lua
        -- cmd(('sil %s %dchi'):format(au, origin_nr))
```
who are evidently trying to call chistory, which will fail in command-line window.

Also, I am unsure as to why the plugin is interacting with the quickfix list at all. I couldn't find any mention in the readme. In some hard to reproduce situations, your plugin will clear the quickfix list and replace it with the search results:
![image](https://user-images.githubusercontent.com/7985687/119406350-a85f0e80-bcb0-11eb-9724-c2152b15fe51.png)
I am guessing most users would rather not have their quickfix list tampered with.

**Comment by kevinhwang91** [comment] 2021-05-25 02:02
I can't reproduce it, please use a minimal config and update the code. I don't think your code is updated.

This plugin build index by `vimgrep` or `vimgrepadd`, this is the simplest way to get all positions in the current buffer.
The side effect of this implement occupies a quickfix list and it must restore the history number of quickfix window.

**Comment by jemag** [comment] 2021-05-26 02:20
Code was updated as per the commit ID I mentioned in the previous post.

It is also reproducible using minimal config, even within docker container.


For example, I reproduced with quickly thrown together Dockerfile:
```Dockerfile
FROM archlinux:base-devel
RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm git cmake unzip bash
RUN useradd -m -g users -s /bin/bash randomuser
WORKDIR /home/randomuser
ADD build.sh build.sh
ADD mini.vim mini.vim
RUN chmod 777 build.sh
RUN chmod 777 mini.vim
USER randomuser
RUN mkdir neovim
RUN mkdir bin
RUN git clone "https://github.com/neovim/neovim" neovim/src
RUN mkdir neovim/build
RUN ls -la
RUN /home/randomuser/build.sh
RUN sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
CMD sleep 9999999
```
where mini.vim
```vim
" use your plugin manager, here is `vim-plug`
call plug#begin('~/.config/nvim/plugged')
Plug 'kevinhwang91/nvim-hlslens'

call plug#end()
lua require('hlslens').setup()
noremap <silent> n <Cmd>execute('normal! ' . v:count1 . 'n')<CR>
            \<Cmd>lua require('hlslens').start()<CR>
noremap <silent> N <Cmd>execute('normal! ' . v:count1 . 'N')<CR>
            \<Cmd>lua require('hlslens').start()<CR>
noremap * *<Cmd>lua require('hlslens').start()<CR>
noremap # #<Cmd>lua require('hlslens').start()<CR>
noremap g* g*<Cmd>lua require('hlslens').start()<CR>
noremap g# g#<Cmd>lua require('hlslens').start()<CR>

" use : instead of <Cmd>
nnoremap <silent> <leader>l :nohlsearch<CR>

```
and build.sh
```sh
#!/bin/bash
ROOT_DIR="$HOME/neovim"
BUILD_DIR="$ROOT_DIR/build"
SOURCE_DIR="$ROOT_DIR/src"

# Extract the source and if there were no errors, remove the previous build.
cd $SOURCE_DIR
git pull &&
	make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX=$BUILD_DIR &&
	rm -rf $BUILD_DIR &&
	make install &&
	git reset --hard; git clean -fxd &&
	cd -
ln -s "$BUILD_DIR/bin/nvim" ~/bin/nvim
```

I can then run the docker image in the background 
`docker run -d jemag/hlslens`
exec into it
`docker exec -it CONTAINER_ID bash`
open nvim and run PlugInstall once within it:
`bin/nvim -u mini.vim`
Then you can just reopen nvim with `-u mini.vim` config and do the reproduction steps from my original post

Here is the docker image if you would like to try it yourself:
https://hub.docker.com/r/jemag/hlslens

**Comment by kevinhwang91** [comment] 2021-05-26 02:38
I'm shame of my arrogance. I never search on the fly in the command line window. I think the issue is fixed now.

BTW, I can see you're serious, so sorry.

**Closed** 2021-05-26 02:40 UTC
Labels: bug

**Comment by kevinhwang91** [comment] 2021-12-03 18:27
It has worked since hlslens use ffi module.
